version: "3.8"

  mosquitto:
    container_name: mosquitto
    build: ./mosquitto
    env_file:
      - ./mosquitto/.env
    ports:
      - 1883:1883
      - 8883:8883
    restart: always
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
