version: "3.8"

  mosquitto:
    container_name: mosquitto
    ports:
      - 1883:1883
    restart: always
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
